version: '3.4'

services:
  api-service:
    container_name: example-api-service
    build:
      context: ./example-service-api
    ports:
      - 80:80
    networks:
      - contract-test-network
  consumer-contract-tests:
    container_name: example-contract-tests-service
    build:
      context: ./contract-tests
    environment: # TODO: change port 9000 if needed
      - SERVICE_UNDER_TEST_HOSTNAME=api-service:80
    entrypoint: ./node_modules/.bin/cucumber-js ./features/**/*.feature
    links:
      - api-service
    networks:
      - contract-test-network
networks:
  contract-test-network:
    driver: bridge